# fly.toml app configuration file generated for app-rough-snowflake-9859 on 2024-10-30T18:11:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-rough-snowflake-9859'
primary_region = 'scl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
